app_name = "Text editor"
dimen = "1200x660"
grey_color = "grey"
pink_color = "pink"
black_color = "black"
red_color = "red"
new_file_label = "New file"
open_file_label = "Open file"
save_file_label = "Save File"
new_file_status = "New file     ..."
ready_label = 'Ready        '
menu_file = "File"
insert_log = "insert"
menu_new = "New"
menu_open = "Open"
menu_save = "Save"
menu_save_as = "Save as"
initdir = "D:/"
filetyp = (("All Files", "*.*"), ("Text Files", "*.txt"),
           ("HTML Files", "*.html"), ("Python Files", "*.py"))
chosen_font = "Helvetica"
an = "center"
padd = 5
dimx = 100
dimy = 28
font_size = 16
cf = '<Control-f>'
cr = '<Control-r>'
cn = '<Control-n>'
co = '<Control-o>'
cs = '<Control-s>'
cq = '<Control-q>'
cj = '<Control-j>'
cg = '<Control-g>'
edit_label = "Edit"
find_label = "Find"
replace_label = "Replace"
replace_all_label = "Replace all"
ctn = "Ctrl+N"
cto = "Ctrl+O"
cts = "Ctrl+S"
ctf = "Ctrl+F"
ctr = "Ctrl+R"
highlight = 'highlight'
close_label = "Close"
pads = "10"
ew = "EW"
ews = "EWS"
on_del = "WM_DELETE_WINDOW"
