app_name = "Text editor"
dimen = "1200x660"
grey_color = "grey"
pink_color = "pink"
black_color = "black"
new_file_label = "New file"
open_file_label = "Open file"
save_file_label = "Save File"
new_file_status = "New file     ..."
translate_status = "Highlight text and press the button to translate ... "
translate_label = "Translate"
ready_label = 'Ready        '
menu_file = "File"
menu_new = "New"
menu_open = "Open"
menu_save = "Save"
menu_save_as = "Save as"
initdir = "D:/"
filetyp = (("All Files", "*.*"), ("Text Files", "*.txt"),
           ("HTML Files", "*.html"), ("Python Files", "*.py"))
eng = "en"
rus = "ru"
chosen_font = "Helvetica"
an = "center"
padd = 5
dimx = 100
dimy = 25
font_size = 16
